version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./:/app
    command: pipenv run python main.py http://example.com
    depends_on:
      - redis
      - worker
    environment:
      - REDIS_URL=redis://redis:6379/0

  worker:
    build: .
    volumes:
      - ./:/app
    command: pipenv run celery -A tasks worker --loglevel=info
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"